import { APIService, Workflow, PolicyRule } from '@/types';

// Initial API Services - Mixed States to Show Realistic Scenario
export const initialServices: APIService[] = [
  {
    id: 'traffic',
    name: 'Traffic API',
    status: 'healthy',
    latency: 120,
    errorRate: 0.01,
    version: 'v2',
    authRequired: true,
    dependencies: ['Sensor API', 'Map Engine'],
    trustScore: 98,
    maxLatency: 800,
    availabilityTarget: 99.99,
  },
  {
    id: 'hospital',
    name: 'Hospital API',
    status: 'degraded',
    latency: 850,
    errorRate: 0.15,
    version: 'v2',
    authRequired: true,
    dependencies: ['Database', 'Auth Service'],
    trustScore: 78,
    maxLatency: 800,
    availabilityTarget: 99.99,
  },
  {
    id: 'ambulance',
    name: 'Ambulance API',
    status: 'healthy',
    latency: 180,
    errorRate: 0.008,
    version: 'v2',
    authRequired: true,
    dependencies: ['GPS', 'Traffic API'],
    trustScore: 97,
    maxLatency: 800,
    availabilityTarget: 99.99,
  },
  {
    id: 'weather',
    name: 'Weather API',
    status: 'critical',
    latency: 2500,
    errorRate: 0.45,
    version: 'v1',
    authRequired: false,
    dependencies: ['Sensor API'],
    trustScore: 62,
    maxLatency: 1000,
    availabilityTarget: 99.5,
  },
  {
    id: 'payment',
    name: 'Payment API',
    status: 'healthy',
    latency: 300,
    errorRate: 0.001,
    version: 'v2',
    authRequired: true,
    dependencies: ['Auth Service', 'Ledger'],
    trustScore: 99,
    maxLatency: 2000,
    availabilityTarget: 99.99,
  },
  {
    id: 'power',
    name: 'Power Grid API',
    status: 'healthy',
    latency: 250,
    errorRate: 0.002,
    version: 'v1.5',
    authRequired: true,
    dependencies: ['Sensor API', 'Control System'],
    trustScore: 94,
    maxLatency: 500,
    availabilityTarget: 99.99,
  },
  {
    id: 'sensor',
    name: 'Sensor API',
    status: 'healthy',
    latency: 100,
    errorRate: 0.03,
    version: 'v2',
    authRequired: false,
    dependencies: [],
    trustScore: 88,
    maxLatency: 500,
    availabilityTarget: 99.0,
  },
  {
    id: 'notification',
    name: 'Notification API',
    status: 'healthy',
    latency: 80,
    errorRate: 0.005,
    version: 'v2',
    authRequired: true,
    dependencies: ['Event Bus', 'Template Engine'],
    trustScore: 95,
    maxLatency: 1000,
    availabilityTarget: 99.5,
  },
  {
    id: 'auth',
    name: 'Identity/Auth API',
    status: 'healthy',
    latency: 120,
    errorRate: 0.001,
    version: 'v3',
    authRequired: true,
    dependencies: [],
    trustScore: 99,
    maxLatency: 500,
    availabilityTarget: 99.99,
  },
  {
    id: 'eventbus',
    name: 'Event Bus',
    status: 'healthy',
    latency: 50,
    errorRate: 0.002,
    version: 'v2',
    authRequired: false,
    dependencies: [],
    trustScore: 97,
    maxLatency: 200,
    availabilityTarget: 99.99,
  },
  {
    id: 'policy',
    name: 'Policy Engine',
    status: 'healthy',
    latency: 180,
    errorRate: 0.001,
    version: 'v1',
    authRequired: false,
    dependencies: [],
    trustScore: 98,
    maxLatency: 500,
    availabilityTarget: 99.99,
  },
  {
    id: 'audit',
    name: 'Audit Service',
    status: 'healthy',
    latency: 90,
    errorRate: 0.001,
    version: 'v2',
    authRequired: false,
    dependencies: ['Event Bus'],
    trustScore: 99,
    maxLatency: 1000,
    availabilityTarget: 99.9,
  },
];

// Initial Workflows
export const initialWorkflows: Workflow[] = [
  {
    id: 'emergency-dispatch',
    name: 'Emergency Ambulance Dispatch',
    description: 'A coordinated workflow for emergency medical response',
    steps: [
      { id: 'step-1', name: 'Sensor Detects Incident', apiId: 'sensor', status: 'pending' },
      { id: 'step-2', name: 'Publish Event', apiId: 'eventbus', status: 'pending' },
      { id: 'step-3', name: 'Validate Identity', apiId: 'auth', status: 'pending' },
      { id: 'step-4', name: 'Check Hospital Capacity', apiId: 'hospital', status: 'pending' },
      { id: 'step-5', name: 'Find Route', apiId: 'traffic', status: 'pending' },
      { id: 'step-6', name: 'Dispatch Ambulance', apiId: 'ambulance', status: 'pending' },
      { id: 'step-7', name: 'Notify Citizen', apiId: 'notification', status: 'pending' },
      { id: 'step-8', name: 'Write Audit Log', apiId: 'audit', status: 'pending' },
    ],
    status: 'pending',
  },
  {
    id: 'ev-charging',
    name: 'EV Charging Coordination',
    description: 'Coordinate EV charging with power grid availability',
    steps: [
      { id: 'step-1', name: 'Check Grid Capacity', apiId: 'power', status: 'pending' },
      { id: 'step-2', name: 'Read Sensor Data', apiId: 'sensor', status: 'pending' },
      { id: 'step-3', name: 'Process Payment', apiId: 'payment', status: 'pending' },
      { id: 'step-4', name: 'Activate Charger', apiId: 'power', status: 'pending' },
      { id: 'step-5', name: 'Send Notification', apiId: 'notification', status: 'pending' },
    ],
    status: 'pending',
  },
  {
    id: 'drone-delivery',
    name: 'Autonomous Drone Delivery',
    description: 'Route and execute autonomous drone delivery with safety checks',
    steps: [
      { id: 'step-1', name: 'Check Weather', apiId: 'weather', status: 'pending' },
      { id: 'step-2', name: 'Check Flight Path', apiId: 'traffic', status: 'pending' },
      { id: 'step-3', name: 'Verify Payment', apiId: 'payment', status: 'pending' },
      { id: 'step-4', name: 'Authorize Agent', apiId: 'auth', status: 'pending' },
      { id: 'step-5', name: 'Send Delivery Notice', apiId: 'notification', status: 'pending' },
    ],
    status: 'pending',
  },
];

// Policy Rules
export const initialPolicies: PolicyRule[] = [
  {
    id: 'policy-1',
    name: 'Emergency Response Priority',
    description: 'Emergency dispatch workflows get priority routing',
    condition: 'workflow.type === "emergency"',
    action: 'priority = "high"; retries = 5',
    active: true,
  },
  {
    id: 'policy-2',
    name: 'Schema Version Validation',
    description: 'Hospital API must return v2 schema',
    condition: 'api === "hospital"',
    action: 'require(schema.version === "v2")',
    active: true,
  },
  {
    id: 'policy-3',
    name: 'Latency SLA Enforcement',
    description: 'Any API over 800ms enters degraded mode',
    condition: 'latency > 800',
    action: 'status = "degraded"; activateFallback()',
    active: true,
  },
  {
    id: 'policy-4',
    name: 'Token Expiration Check',
    description: 'Reject requests with expired tokens',
    condition: '!tokenValid()',
    action: 'reject(); logSecurityEvent()',
    active: true,
  },
  {
    id: 'policy-5',
    name: 'Untrusted Callback Blocking',
    description: 'Block callbacks from untrusted domains',
    condition: '!domainTrusted(callback.domain)',
    action: 'block(); alert("security")',
    active: true,
  },
  {
    id: 'policy-6',
    name: 'Duplicate Event Rejection',
    description: 'Reject duplicate event IDs within 5 minutes',
    condition: 'isDuplicate(eventId)',
    action: 'reject(); metrics.duplicateDrop++',
    active: true,
  },
  {
    id: 'policy-7',
    name: 'Audit Trail Requirement',
    description: 'All dispatch actions must be auditable',
    condition: 'isDispatchAction()',
    action: 'require(auditLog); request.auditRequired = true',
    active: true,
  },
];

// Chaos Options
export const chaosOptions = [
  {
    id: 'latency-spike',
    name: 'Inject Latency Spike',
    description: 'Add 3+ seconds to Traffic API',
    icon: 'Zap',
    color: 'neon-orange',
  },
  {
    id: 'break-contract',
    name: 'Break Contract',
    description: 'Hospital API returns v1 schema (expected v2)',
    icon: 'AlertTriangle',
    color: 'neon-red',
  },
  {
    id: 'expire-token',
    name: 'Expire Token',
    description: 'Invalidate ambulance agent credentials',
    icon: 'Lock',
    color: 'neon-red',
  },
  {
    id: 'ddos-simulation',
    name: 'Simulate DDoS',
    description: 'Flood event bus with duplicate events',
    icon: 'AlertOctagon',
    color: 'neon-red',
  },
  {
    id: 'drop-events',
    name: 'Drop Events',
    description: '40% of events silently fail',
    icon: 'Droplets',
    color: 'neon-orange',
  },
  {
    id: 'duplicate-events',
    name: 'Duplicate Events',
    description: 'Send same event twice',
    icon: 'Copy',
    color: 'neon-orange',
  },
  {
    id: 'timeout',
    name: 'Service Timeout',
    description: 'Payment API hangs for 30 seconds',
    icon: 'Clock',
    color: 'neon-red',
  },
  {
    id: 'version-drift',
    name: 'Version Drift',
    description: 'API returns v1 response, client expects v2',
    icon: 'GitBranch',
    color: 'neon-orange',
  },
  {
    id: 'schema-mismatch',
    name: 'Schema Mismatch',
    description: 'Response fields do not match contract',
    icon: 'FileX',
    color: 'neon-orange',
  },
  {
    id: 'kill-payment',
    name: 'Kill Payment API',
    description: 'Complete service outage',
    icon: 'PowerOff',
    color: 'neon-red',
  },
  {
    id: 'compromise-sensor',
    name: 'Compromise Sensor',
    description: 'Inject fake sensor data',
    icon: 'AlertCircle',
    color: 'neon-red',
  },
  {
    id: 'event-storm',
    name: 'Trigger Event Storm',
    description: 'Overload event bus with rapid events',
    icon: 'CloudRain',
    color: 'neon-red',
  },
];
